version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "000000"
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "8080:5432"
  web:
    image: node-crud-git
    depends_on:
      - db
    ports:
      - "3000:3000"
