version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "0000"
      POSTGRES_USER: dhruvik
      POSTGRES_DB: nodeauth

  app:
    image: nodeauth
    ports:
      - "13000:3000"
